### ISSUE TITLE
アウトライン項目の内容を編集できるようにする

### ISSUE THREAD

**Issue by etoal83** [etoal83/elm-outliner#4]
## ☑️ ToDo

- [ ] 項目はクリックまたはタップで描画モードから編集モードへ切り替わり、内容の編集が可能となる
- [ ] カーソルを上下に移動させると編集モードになっている現在の項目は描画モードへ切り替わり、移動先の項目が編集モードへ切り替わる
- [ ] カーソルの移動または`blur`イベントによって項目が編集モードから表示モードに切り替わると、その項目の内容が保存される
- [ ] 編集モードで改行すると、現在カーソルがいる項目の直下に新規の項目が作られる
  - [ ] 編集モードとなっている項目の末尾で改行した場合、空白の新規項目が作られる
  - [ ] 編集モードとなっている項目の先頭あるいは文中で改行した場合、新規項目が作られカーソルの現在位置よりも後ろにある文字列が新規項目へ移動する
- [ ] 空白の項目にカーソルがある状態で`backspace`キーまたは`delete`キーが押されると、その項目は削除される
- [ ] 項目が1つもないアウトラインのページを開いたときは、空の項目がフォーカスされて編集モードとなっている

cf. https://github.com/etoal83/elm-outliner/issues/3#issuecomment-1031634097

**Comment by etoal83** [comment]
### 描画済みのhtml要素を編集するには？

- [contenteditable 属性 - MDN Web Docs](https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/contenteditable)
